### ISSUE TITLE
What is the function of this code?

### ISSUE THREAD

**Issue by std-s** [ekazaev/ChatLayout#53] opened 2023-08-03 10:33 UTC
```swift
guard currentInterfaceActions.options.isEmpty else {
            print("A:\(Date())")
            let reaction = SetActor<Set<InterfaceActions>, ReactionTypes>.Reaction(type: .delayedUpdate,
                                                                                   action: .onEmpty,
                                                                                   executionType: .once,
                                                                                   actionBlock: { [weak self] in
                guard let self else {
                    return
                }
                print("B:\(Date())")
                processUpdates(with: sections, animated: animated, requiresIsolatedProcess: requiresIsolatedProcess, completion: completion)
                print("C:\(Date())")
            })
            currentInterfaceActions.add(reaction: reaction)
            return
        }
```

**Comment by ekazaev** [comment] 2023-08-03 10:58
Hi @std-s If there is some interface action happens when you can not update the collection view (for example you are updating the content offset animatingly and the state of collection view is undefined in that moment) if at this very moment an update comes, it stores it, and the reaction will be called when the currentInterfaceActions are empty.

**Comment by std-s** [comment] 2023-08-04 02:39
> ```swift
> guard currentInterfaceActions.options.isEmpty else {
>             print("A:\(Date())")
>             let reaction = SetActor<Set<InterfaceActions>, ReactionTypes>.Reaction(type: .delayedUpdate,
>                                                                                    action: .onEmpty,
>                                                                                    executionType: .once,
>                                                                                    actionBlock: { [weak self] in
>                 guard let self else {
>                     return
>                 }
>                 print("B:\(Date())")
>                 processUpdates(with: sections, animated: animated, requiresIsolatedProcess: requiresIsolatedProcess, completion: completion)
>                 print("C:\(Date())")
>             })
>             currentInterfaceActions.add(reaction: reaction)
>             return
>         }
> ```
hi, @ekazaev 
I printed the current time of three locations A, B, C; found that A and B took a lot of time before, why is that?

**Comment by ekazaev** [comment] 2023-08-04 11:02
@std-s  Detailed answer you can probably find here. https://github.com/ekazaev/ChatLayout/issues/51 It s a bit vagua as at the begining I couldnt understadn the question. But the problem is that you need to populate cells syncroniously before the push animation starts. That is the issue there.

**Comment by ekazaev** [comment] 2023-08-08 15:14
@std-s Anything else I can help you with or it is safe to close the issue?

**Comment by std-s** [comment] 2023-08-10 08:11
> @std-s Detailed answer you can probably find here. #51 It s a bit vague as at the begining I couldnt understadn the question. But the problem is that you need to populate cells **syncroniously** before the push animation starts. That is the issue there. And the function you are referencing to is **asynchorios**.
> 
> The difference in time there is because B will be called only when the `currentInterfaceActions` are empty again and after the previous animating insertion is completed. It is not the issue there.

hi, the relevant method here is not applicable. The effect is still as shown in the video above.

**Comment by std-s** [comment] 2023-08-10 08:14
How to reduce the time spent from A to B is what I want.

**Comment by ekazaev** [comment] 2023-08-10 16:00
@std-s You need to add a flag there and avoid async processing on appearance. Keep in mind it will require change in the Chat Controller as well. You want to get messages and update the collection view before the pushing animation starts.

**Comment by std-s** [comment] 2023-08-15 07:08
> @std-s You need to add a flag there and avoid async processing on appearance. Keep in mind it will require change in the Chat Controller as well. You want to get messages and update the collection view before the pushing animation starts.
> 
> This is what you want to get [gif](https://github.com/ekazaev/ChatLayout/assets/20243258/58ba4d8a-2fed-4dd8-b40e-d436e73a9e1c)
> 
> 1. So `chatController.loadInitialMessages {` - is asynchronious function. You need a **synchronous** for the initial appearance. Synchronous means `let sections = chatController.getCachedMessages()`
> 2. then **add a flag** to `processUpdates` that on initial appearance it would ignore the `currentInterfaceActions.options` count like `guard ignoreInterfaceActions || currentInterfaceActions.options.isEmpty else {` and process those changes anyway. Keep this flag off for all the other times.
> 3. Keep in mind that you must precess those `sections` **synchronously** from the first call of `viewDidLayoutSubviews`. It is the first time when your UINavigationController sets the correct size of the ChatViewController inside of it. Otherwise the view size is not correct.

👌，Ok, I'll try these methods.

**Comment by std-s** [comment] 2023-08-15 07:19
For now, that's the only way to deal with it.

**Comment by ekazaev** [comment] 2023-08-15 12:47
@std-s  My pleasure. good luck

**Closed** 2023-08-15 12:50 UTC
Labels: help wanted
