### ISSUE TITLE
Message bubble jumps when reloading collection view

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#67] opened 2024-03-03 18:10 UTC
Hi @ekazaev 

Do you perhaps have any idea why my message bubble jumps after propagating messages and processing updates (reloading collection view), my app is based off example app. See issue in video below. Feel free to ask for any part of code. Thanks.

https://github.com/ekazaev/ChatLayout/assets/66596779/ac0d1909-0713-4f6e-816d-8fb6ed6a4de8

**Comment by ekazaev** [comment] 2024-03-04 10:58
@ElrB Hi, Can you please reproduce this behaviour in the example app so I could investigate? Could it be that you are changing a spacing value somehow?

**Comment by ekazaev** [comment] 2024-03-04 18:09
As you can see in the Example app everything is working as expected.
https://github.com/ekazaev/ChatLayout/assets/20243258/a0d7125b-e2e0-4b30-a898-7e1bd565e4a0

**Comment by ElrB** [comment] 2024-03-06 14:27
Hi @ekazaev 

My latest investigation is that these jumps occur when the keyboard is not showing, and when the keyboard is showing, the jumps do not happen. I haven't fully confirmed it yet, but it sometimes looks like it also only happens when there are a few messages in the collection view (messages not fully covering the entire collection view). See below.


https://github.com/ekazaev/ChatLayout/assets/66596779/ba0d730b-1745-47f2-b547-065d96dab371

**Comment by ekazaev** [comment] 2024-03-06 16:37
@ElrB Unfortunately, suggesting that you are doing something wrong with spacing values or there is something wrong with the views within cells, I cant come with better assumption. You need to reproduce it in the Example app so I can provide you further help.

To try to eliminate first problem - try to remove any changes in interItem/sections you are doing and check the app. If it helps - check what you are doing wrong with the spacing.
To eliminate potential problem if there is something wrong with the views in the cells that may affect their measurements - try to set exact values (yeah they all will have same height and will look) and check if the jumping persists. If not - check what view within the cell may cause it.

If you are still confused - reproduce this issue in the example app and we can continue from there.

**Comment by ElrB** [comment] 2024-03-06 21:02
@ekazaev the confusing part is why the jumps are only happening when keyboard is not showing. 

My interItem/section is the same as example app. 
It’s hard to reproduce the issue as I don’t know the cause. 

I don’t believe the issue is with the cell view heights because during the jumps the views’ heights do not change (see video below in slow motion). 



https://github.com/ekazaev/ChatLayout/assets/66596779/3a189af1-038f-4f49-bd11-5a22df6dda45

**Comment by ekazaev** [comment] 2024-03-07 09:47
@ElrB I understand. But I don't see your code to diagnose something. So unless you reproduce it in the example app - I cant suggest anything more than I wrote you above.

**Comment by ElrB** [comment] 2024-03-08 22:27
Hi @ekazaev 

I did a few debugs; first I replaced all the code in processUpdates with a simple collectionView.reload() and the jumps were not happening, but of course there are also no insertion animation.

Then after going to the function below and putting print statements in (if !changeset.elementDeleted.isEmpty and if !changeset.elementInserted.isEmpty) they both get called when I actually only have inserted items, then I also tried deleting a message and both still got called but actually deleted item from collection view. So am thinking this could be causing the issue.

I also tested on example app code with placing same print statement but there all is working properly, elementInserted gets called alone when insertion occurs.

I am not sure why if !changeset.elementDeleted.isEmpty is getting called if no deletion has occurred in the data source. Maybe I am creating my data source items incorrectly. Could it be?


func reload<C>(
        using stagedChangeset: StagedChangeset<C>,
        interrupt: ((Changeset<C>) -> Bool)? = nil,
        onInterruptedReload: (() -> Void)? = nil,
        completion: ((Bool) -> Void)? = nil,
        setData: (C) -> Void
    ) {
        if case .none = window, let data = stagedChangeset.last?.data {
            setData(data)
            if let onInterruptedReload {
                onInterruptedReload()
            } else {
                reloadData()
            }
            completion?(false)
            return
        }

        let dispatchGroup: DispatchGroup? = completion != nil
            ? DispatchGroup()
            : nil
        let completionHandler: ((Bool) -> Void)? = completion != nil
            ? { _ in
                dispatchGroup!.leave()
            }
            : nil

        for changeset in stagedChangeset {
            if let interrupt, interrupt(changeset), let data = stagedChangeset.last?.data {
                setData(data)
                if let onInterruptedReload {
                    onInterruptedReload()
                } else {
                    reloadData()
                }
                completion?(false)
                return
            }

            performBatchUpdates({
                setData(changeset.data)
                dispatchGroup?.enter()

                if !changeset.sectionDeleted.isEmpty {
                    deleteSections(IndexSet(changeset.sectionDeleted))
                }

                if !changeset.sectionInserted.isEmpty {
                    insertSections(IndexSet(changeset.sectionInserted))
                }

                if !changeset.sectionUpdated.isEmpty {
                    reloadSections(IndexSet(changeset.sectionUpdated))
                }

                for (source, target) in changeset.sectionMoved {
                    moveSection(source, toSection: target)
                }

                if !changeset.elementDeleted.isEmpty {
                    print("elementDeleted")
                    
                    deleteItems(at: changeset.elementDeleted.map {
                        IndexPath(item: $0.element, section: $0.section)
                    })
                }

                if !changeset.elementInserted.isEmpty {
                    print("elementInserted")

                    insertItems(at: changeset.elementInserted.map {
                        IndexPath(item: $0.element, section: $0.section)
                    })
                }

                if !changeset.elementUpdated.isEmpty {
                    let indexPaths = changeset.elementUpdated.map {
                        IndexPath(item: $0.element, section: $0.section)
                    }
                    if #available(iOS 15.0, *),
                       enableReconfigure {
                        reconfigureItems(at: indexPaths)
                        (collectionViewLayout as? CollectionViewChatLayout)?.reconfigureItems(at: indexPaths)
                    } else {
                        reloadItems(at: indexPaths)
                    }
                }

                for (source, target) in changeset.elementMoved {
                    moveItem(at: IndexPath(item: source.element, section: source.section), to: IndexPath(item: target.element, section: target.section))
                }
            }, completion: completionHandler)
        }
        dispatchGroup?.notify(queue: .main) {
            completion!(true)
        }
    }

**Comment by ekazaev** [comment] 2024-03-09 14:24
@ElrB With `reloadData` the jump doesnt happen because it happens without animation. I can assume then that the problem in the dataset that sends improper commands to the collection view. If you don't expect deletion there, and according to what I see you dont - you need to find out why it happens. 
I suggest you as well to put `print("\(#function) \(updateItems)")` to the `prepare(forCollectionViewUpdates updateItems: [UICollectionViewUpdateItem])` of the `CollectionViewChatLayout` and compile like this - it will help you to understand what commands you are sending to the collection view.

**Comment by ElrB** [comment] 2024-03-09 15:07
@ekazaev I have resolved the issue. 
The issue was that I was creating section items with a new differenceIdentifier every time processUpdates/reload collection view. So source and target sections items all had different identifiers, resulting into the above issue. 

The identifiers am talking about is the ones like below.

extension CellTopTitle: Differentiable {
    public var differenceIdentifier: Int {
        id
    }

    public func isContentEqual(to source: CellTopTitle) -> Bool {
        self == source
    }
}

**Comment by ekazaev** [comment] 2024-03-11 10:43
@ElrB I am happy to hear that you found the issue. I can only remind you what the README says and close the issue

> If you see a strange or unexpected animation during the updates, check your data model and the commands you send to the UICollectionView's performBatchUpdates. Especialy if you are using some diffing algorithms like [DifferenceKit](https://github.com/ra1028/DifferenceKit). It is very possible that you are sending delete/insert commands when you expect to see reload. The easiest way to check it is by adding print("\(updateItems)") into ChatLayout.prepare(forCollectionViewUpdates:) method. ChatLayout doesn't know what you expected to see. It just processes your changes according to the commands it has received.

**Closed by ekazaev** 2024-03-11 10:43 UTC
Labels: help wanted
