### ISSUE TITLE
question] position & scrolling  

### ISSUE THREAD

**Issue by LEEKIWAN** [ekazaev/ChatLayout#37] opened 2022-10-31 06:04 UTC
https://user-images.githubusercontent.com/30687224/198941595-f622ebd0-db0f-4a52-9807-5297461f202a.mp4

hello

After loading data, move to the "Read this far" cell. However, there is a phenomenon of tingling when scrolling from top to bottom after not going to the correct movement.

Conversely, there is no issue when scrolling from bottom to top after loading. I'll attach a video and some code, so please check it out, thank you.

celll is just created by autolayout 

```Swift
 var dataInput: [Section] {
        get { return data }
        set {
            let changeset = StagedChangeset(source: data, target: newValue)
            
            collectionView.reload(using: changeset) { data in
                self.data = data
            }
        }
    }
```

```swift
  collectionView.isPrefetchingEnabled = false
        collectionView.alwaysBounceVertical = true
        collectionView.automaticallyAdjustsScrollIndicatorInsets = true
        collectionView.translatesAutoresizingMaskIntoConstraints = false
```

```swift 
 UIView.performWithoutAnimation {
            dataInput = changedData
        }

        if let index = scrollToIndexPath {
            collectionView.scrollToItem(at: index, at: .centeredVertically, animated: false)
// scroll to ReadToHear Item -> but not centered and somtimes not visible
        } else {
            collectionView.scrollToLast(animated: false)
        }

```

**Comment by ekazaev** [comment] 2022-10-31 23:31
@LEEKIWAN Hi. Ill try to have a look tomorrow. I haven’t seen anything like this before. Technically If you start the Example app, rotate it to album mode, then scroll it up enough like 3-4 previous messages loads. Then rotate it back to portrait mode it should behave like you described as it doesn’t know the exact size of the cells below anymore and computes the layout on fly like in your case. But it behaves normally so I would exclude the Layout itself as the main suspect for now. Try to provide more information about your implementation or try to reproduce your case in the example app. It should help me to help you.

**Comment by ekazaev** [comment] 2022-11-02 11:22
@LEEKIWAN I could not reproduce your behaviour. Do you have any update for me?

**Comment by LEEKIWAN** [comment] 2022-11-03 03:18
Thank you for quick response.
I wanted to create a separate project and share it, but it took too much time, so I stopped.
I haven't solved it yet, but I'll keep looking at the sample project and try to solve it.
thank you

**Comment by ekazaev** [comment] 2022-11-03 10:57
@LEEKIWAN Good luck. Keep me posted.

**Comment by ekazaev** [comment] 2022-11-07 11:29
@LEEKIWAN Ill close this issue for now. Feel free to reopen it if you have more information how to reproduce it.

**Closed by ekazaev** 2022-11-07 11:29 UTC
Labels: question

**Comment by LEEKIWAN** [comment] 2022-11-18 01:48
@ekazaev I created a sample project that reproduces it.
Could you please check if possible? 

https://github.com/LEEKIWAN/ChatExam
