### ISSUE TITLE
Xcode version  13.2 build issue

### ISSUE THREAD

**Issue by farshadmb** [ekazaev/ChatLayout#36] opened 2022-10-06 23:52 UTC
Hi bro,
I use Xcode `13.2` as a daily basis IDE. however, I met a compile error `segmentation fault 11` for some files such as `StateController` line 675 columns 13. I've also realized that there is no Xcode backward compatibility. I've wondered so much as well. 

Do you have any clue what's wrong with it?

**Comment by farshadmb** [comment] 2022-10-07 10:44
@ekazaev I highly encourage you to create a GitHub action workflow to run test cases on a specified Xcode version. 
I would like to create one for you.

**Comment by ekazaev** [comment] 2022-10-07 11:18
`segmentation fault 11` It is a bug in the compiler at the first place, but it is not even important in this case. Another thing is that I have already moved to swift 5.7 in July where that expression is a valid string. I can fix it but you may get next problem with  `#unavailable` or something like this. So I am not sure if I have to do something about it as if you are using the previous version of the compiler, probably it worth to use older version of the library that is written in swift 5.2. There is nothing wrong with it and you are clearly not interested in the fixes added for IOS 16 SDK that were added later. 

So I am not sure what action to take here TBH. @farshadmb What do you think?

Regarding GitHub action - please do. Ill appreciate it.I used travis while it was free. But I dont have any CI any more.

**Comment by farshadmb** [comment] 2022-10-07 15:30
@ekazaev I will do it as fast as I could. also, I provide a GitHub action for this repository as well because Github makes totally free for open projects such as yours.

**Comment by ekazaev** [comment] 2022-10-07 17:54
@farshadmb Thank you. Ill also have a look when ill have time. 
But I assure you that there is nothing wrong with the older version of the library, so if you can not update your xcode just temporary - just use the older version. There was only one problematic version where i had a typo in a binary search algorithm and i think i fixed it in swift 5.2 version. But its such a small defect that you may never even hit it. And I assume you’ll be able to update your compiler version and the library later, before the release of your application. 

Best of luck.

**Comment by ekazaev** [comment] 2022-10-10 11:20
@farshadmb Morning. I have checked the library in XCode 13.2. The issue is not in the line that you pointed our but in the use of the associated values in the models and it is clearly a compiler but. But anyways I made for you a version of the library that compiles in XCode 13.2. You can check it out in the branch `origin/xcode_13_2_issue`. 

Please, let me know if I can help you further.

**Comment by ekazaev** [comment] 2022-10-13 15:31
@farshadmb Ill close this issue for now. Hope the branch I provided will cover your needs. Please dont hesitate to reopen this issue if you need any further assistance.

**Closed by ekazaev** 2022-10-13 15:31 UTC
Labels: question

**Comment by farshadmb** [comment] 2022-10-13 16:42
Thanks, I will work on it in my spare time, however, my plate is so full.

**Comment by ekazaev** [comment] 2022-10-14 09:50
I know your pain :) . Best of luck.
